### ISSUE TITLE
ParticipantsIdentity -> player -> teamId does not exists

### ISSUE THREAD

**Issue by FernandoRomero11** [dolejska-daniel/riot-api-league#2]
The variable is declared but when im trying to get the value it returns "".

**Comment by dolejska-daniel** [comment]
Hello, thank you for the issue - it would be nice if you provided additional information about your problem. At least the endpoint you are calling (best with values and IDs you are using).

**Comment by FernandoRomero11** [comment]
The problem is in playerDTO. We have teamId when the endpoint is not serving it. I hope I've helped!
![image](https://user-images.githubusercontent.com/56682378/114845538-255ab680-9ddc-11eb-8c50-7470c007b6e2.png)
![image](https://user-images.githubusercontent.com/56682378/114845601-31df0f00-9ddc-11eb-9c73-1a7f9dd4af97.png)

**Comment by FernandoRomero11** [comment]
All I know is that when I loop throught "ParticipantIdentities", and i get participant-> player-> teamId returns empty.
![image](https://user-images.githubusercontent.com/56682378/114846746-44a61380-9ddd-11eb-9a95-3490d633a64c.png)

**Comment by dolejska-daniel** [comment]
`Match v4` actually uses property `participants` not `participantIdentities` to store such information.
```php
$match->participants[0]->teamId;
```

**Comment by FernandoRomero11** [comment]
Ok i got confused because of my IDE, im sorry. Thanks for your time!

**Comment by dolejska-daniel** [comment]
@FernandoRomero11 I have added information about property availability to their annotation. This should help with Riot's somewhat inconsistent API.
