### ISSUE TITLE
Runes

### ISSUE THREAD

**Issue by FernandoRomero11** [dolejska-daniel/riot-api-league#3]
Is there any possibility to get runesId from a participant of a match? Match->Participants[0]->stats->runes returning null.

**Comment by dolejska-daniel** [comment]
The `runes` field refers to outdated runes from before 2018 when runes reforged came along. Information about Runes Reforged can be found in `perk*` fields.

**Comment by dolejska-daniel** [comment]
I'll close this issue since there were no further questions for some time. Next time, please, close the issue yourself after the problem has been solved/question answered. Thanks! 😊
